# Generated by Django 4.0.5 on 2024-01-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pedido_delete_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
