# Generated by Django 4.0.5 on 2024-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_pedido_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
