# Generated by Django 4.0.5 on 2024-01-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_pedidoitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="products",
            field=models.ManyToManyField(
                through="store.ProductQuantity", to="store.product"
            ),
        ),
        migrations.DeleteModel(
            name="PedidoItem",
        ),
        migrations.AddField(
            model_name="productquantity",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.pedido"
            ),
        ),
        migrations.AddField(
            model_name="productquantity",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
    ]
