# Generated by Django 4.0.5 on 2024-01-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productquantity_pedido_products_delete_pedidoitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='products',
        ),
        migrations.AddField(
            model_name='pedido',
            name='order_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
    ]
