# Generated by Django 4.0.5 on 2024-01-22 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_rename_order_carrinho_rename_orderitem_carrinhoitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="digital",
        ),
    ]
