# Generated by Django 4.0.5 on 2024-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_tamanhoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
