# Generated by Django 4.0.5 on 2024-01-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='order_items',
        ),
    ]
