# Generated by Django 4.0.5 on 2024-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0028_remove_pedido_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinhoitem",
            name="total",
            field=models.FloatField(default=0),
        ),
    ]
