# Generated by Django 4.0.5 on 2024-02-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_enderecoenvio_order_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
