# Generated by Django 4.0.5 on 2024-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(help_text='Alt da imagem', max_length=255)),
            ],
        ),
    ]
