# Generated by Django 4.0.5 on 2024-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_original',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
