# Generated by Django 4.0.5 on 2024-02-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_produto_valor_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, choices=[('O', 'Olympikus'), ('M', 'Mormaii'), ('C', 'Converse'), ('N', 'Nike'), ('A', 'Adidas'), ('P', 'Puma'), ('A', 'Asics'), ('Z', 'Mizuno'), ('V', 'Vans'), ('F', 'Fila')], max_length=1, null=True),
        ),
    ]
