# Generated by Django 4.0.5 on 2024-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='departamento_bs',
            field=models.CharField(blank=True, choices=[('E', 'Esporte'), ('C', 'Calçados'), ('A', 'Acessórios'), ('R', 'Corrida'), ('F', 'Futebol')], max_length=1, null=True),
        ),
    ]
