# Generated by Django 4.0.5 on 2024-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_produto_departamento_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
