# Generated by Django 4.0.5 on 2024-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_produto_image1_produto_image2_produto_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
