# Generated by Django 4.0.5 on 2024-06-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importante',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
