# Generated by Django 4.0.5 on 2024-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_tamanhoproduto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=1400, null=True),
        ),
    ]
